project_id = "zmnttrxjyfctzjvhoukh"

[functions.parse-voice-quote]
verify_jwt = false

[functions.accept-quote]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true